name: dribbble_challenge
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0+1
  flutter_riverpod: ^2.4.0
  freezed: ^2.4.2
  timelines: ^0.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  sliding_up_panel: ^2.0.0+1
  flex_color_scheme: ^7.3.1
  device_preview: ^1.1.0
  otp_pin_field: ^1.2.0+2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.8
  # google_maps_flutter: ^2.3.1
  custom_map_markers: ^0.0.2+1
  http: ^1.1.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.1.2
  intl: ^0.19.0
  flutter_timezone: ^1.0.6
  get_it: ^7.6.0
  printing: ^5.14.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.5.10
  external_path: ^1.0.3
  permission_handler: ^10.4.3
  syncfusion_flutter_pdf: ^29.1.37
  universal_html: ^2.2.4
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  riverpod_lint: ^2.0.4
  custom_lint: ^0.6.4
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/recipes.json
    - assets/images/
    - assets/img/
    - assets/images/rice.png
    - assets/icons/
    - assets/items/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/font/Metropolis-Regular.otf
        - asset: assets/font/Metropolis-Medium.otf
          weight: 500
        - asset: assets/font/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/font/Metropolis-Bold.otf
          weight: 700
        - asset: assets/font/Metropolis-ExtraBold.otf
          weight: 800
